spring:
  application:
    name: KafkaBatchListenerExample
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
    consumer:
      group-id: kafka-test-batch-group-id
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  kafka-topics: kafka-test-batch-topic

management:
  endpoints.web.exposure.include: "*"
  server.port: 8081
  observations:
    enable:
      all: true
# TODO: Check if this even needed when tracing start working
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
      produce: w3c
      consume: w3c

logging:
#  level.org.apache.kafka: DEBUG
  pattern:
#    console: "[%d{dd.MM.yyyy|HH:mm:ss.SSS}] %highlight(%-5level) [%blue(%t)] %yellow(%C{1}):[%X{traceId} %X{spanId}]: %msg%n%throwable"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %yellow([${spring.application.name},%X{traceId},%X{spanId}]) %-5p %c{1} - %m%n"