spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-test-batch-group-id
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  kafka-topics: kafka-test-batch-topic

management:
  endpoints.web.exposure.include: "*"
  server.port: 8081